{% set name = "goosebib" %}
{% set version = "0.3.5" %}
{% set sha256 = "48183447c3bc7373656d4c9a98d6fb0187995dab029f74480b0b355980997a2b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GooseBib/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - GbibCheckAuthors = GooseBib.cli.GbibCheckAuthors:main
    - GbibCheckLink = GooseBib.cli.GbibCheckLink:main
    - GbibClean = GooseBib.cli.GbibClean:main
    - GbibList = GooseBib.cli.GbibList:main
    - GbibParse = GooseBib.cli.GbibParse:main
    - GbibSelect = GooseBib.cli.GbibSelect:main
    - GbibSelectAlias = GooseBib.cli.GbibSelectAlias:main

requirements:
  host:
    - python >=3
    - pip
    - setuptools
  run:
    - python >=3
    - docopt
    - click
    - requests
    - bibtexparser

test:
  commands:
    - GbibCheckAuthors --help
    - GbibCheckLink --help
    - GbibClean --help
    - GbibList --help
    - GbibParse --help
    - GbibSelect --help
    - GbibSelectAlias --help

about:
  home: https://github.com/tdegeus/GooseBib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple command-line tools to clean-up BibTeX files.
  description: Simple command-line tools to clean-up BibTeX files.
  doc_url: https://github.com/tdegeus/GooseBib
  dev_url: https://github.com/tdegeus/GooseBib

extra:
  recipe-maintainers:
    - tdegeus
