{% set version = "0.9.4" %}

package:
  name: goosebib
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GooseBib/archive/v{{ version }}.tar.gz
  sha256: 99724c7d082fa6f205270e2a2a30dd01ce4106acb428d9930d7eb936d0bf92cd

build:
  number: 0
  noarch: python
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - GbibClean = GooseBib.bibtex:GbibClean
    - GbibDiscover = GooseBib.bibtex:GbibDiscover
    - GbibCheckAuthors = GooseBib.cli.GbibCheckAuthors:main
    - GbibCheckKeys = GooseBib.cli.GbibCheckKeys:main
    - GbibCheckLink = GooseBib.cli.GbibCheckLink:main
    - GbibList = GooseBib.cli.GbibList:main
    - GbibParse = GooseBib.cli.GbibParse:main
    - GbibSelect = GooseBib.cli.GbibSelect:main
    - GbibSelectAlias = GooseBib.cli.GbibSelectAlias:main
    - GbibShowAuthorRename = GooseBib.bibtex:GbibShowAuthorRename

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=45
    - setuptools_scm >=6.2
  run:
    - arxiv
    - bibtexparser
    - click
    - docopt
    - gitpython
    - numpy
    - python >=3.6
    - pyyaml
    - requests
    - tqdm

test:
  imports:
    - GooseBib
  commands:
    - pip check
    - python -c "import GooseBib; assert GooseBib.version == '{{ version }}'"
    - GbibClean --version | grep {{ version }}
    - GbibDiscover --version | grep {{ version }}
    - GbibCheckAuthors --help
    - GbibCheckKeys --help
    - GbibCheckLink --help
    - GbibList --help
    - GbibParse --help
    - GbibSelect --help
    - GbibSelectAlias --help
    - GbibShowAuthorRename --help
  requires:
    - git
    - pip

about:
  home: https://github.com/tdegeus/GooseBib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple command-line tools to clean-up BibTeX files.
  description: Simple command-line tools to clean-up BibTeX files.
  doc_url: https://github.com/tdegeus/GooseBib
  dev_url: https://github.com/tdegeus/GooseBib

extra:
  recipe-maintainers:
    - tdegeus
